//
//  StreamifyStyleKit.h
//  StreamifyStyleKit
//
//  Created by jnagel on 5/17/15.
//  Copyright (c) 2015 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StreamifyStyleKit : NSObject

// Colors
+ (UIColor*)spotifyGreen;

// Drawing Methods
+ (void)drawHeaderViewWithFrame: (CGRect)frame;

// Generated Images
+ (UIImage*)imageOfHeaderViewWithFrame: (CGRect)frame;

@end
